### ISSUE TITLE
terminate called after throwing an instance of 'Xbyak::Error'

### ISSUE THREAD

**Issue by prestonvanloon** [herumi/bls-eth-go-binary#25]
Hi,

This error has shown up in our fuzz testing. It's only been reported once and has not affected any users at runtime.
```

ERR Pack bad n=0(0)
--
  | terminate called after throwing an instance of 'Xbyak::Error'
  | what():  bad parameter
  | AddressSanitizer:DEADLYSIGNAL
  | =================================================================
  | ==2441==ERROR: AddressSanitizer: ABRT on unknown address 0x000000000989 (pc 0x7fba67c117bb bp 0x0000023f4d00 sp 0x7fba644fe160 T1)
  | SCARINESS: 10 (signal)
  | #0 0x7fba67c117ba in gsignal
  | #1 0x7fba67bfc534 in abort
  | #2 0x7fba67fda982  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x8c982)
  | #3 0x7fba67fe08c5  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x928c5)
  | #4 0x7fba67fe0900  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x92900)
  | #5 0x7fba67fe0b33  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x92b33)
  | #2 0x10d3f0e in Xbyak::util::Pack::operator[](unsigned long) const
  | #3 0x10ef6e6 in void mcl::fp::FpGenerator::add_rm<Xbyak::RegExp>(Xbyak::util::Pack const&, Xbyak::RegExp const&, bool)
  | #4 0x10ede1f in mcl::fp::FpGenerator::gen_raw_fp_add(Xbyak::RegExp const&, Xbyak::RegExp const&, Xbyak::RegExp const&, Xbyak::util::Pack const&, bool)
  | #5 0x10ebb11 in mcl::fp::FpGenerator::gen_fp_add_le4()
  | #6 0x1091431 in mcl::fp::FpGenerator::gen_fp_add()
  | #7 0x108dee6 in mcl::fp::FpGenerator::init_inner(mcl::fp::Op&)
  | #8 0x108cdcd in mcl::fp::FpGenerator::init(mcl::fp::Op&)
  | #9 0x1031fe8 in mcl::fp::Op::init(mcl::VintT<mcl::vint::FixedBuffer<unsigned long, 768ul> > const&, unsigned long, int, mcl::fp::Mode, unsigned long)
  | #10 0xf87129 in mcl::FpT<mcl::bn::local::FrTag, 256ul>::init(bool*, int, mcl::VintT<mcl::vint::FixedBuffer<unsigned long, 768ul> > const&, mcl::fp::Mode)
  | #11 0xf936e0 in mcl::bn::local::Param::init(bool*, mcl::CurveParam const&, mcl::fp::Mode)
  | #12 0xf6cdc8 in blsInit
  | #13 0xf474ee in _cgo_592780cd2cc3_Cfunc_blsInit

```

Do you think this is a potential issue?

**Comment by herumi** [comment]
I think that the reason is the same as https://github.com/herumi/bls-eth-go-binary/issues/24

**Comment by herumi** [comment]
Is this the same code at https://github.com/herumi/bls-eth-go-binary/issues/24#issuecomment-660739413 ?

**Comment by prestonvanloon** [comment]
Yep, same code

**Comment by herumi** [comment]
How did you call `bls.Init`? This function is not thread-safe, then calling simultaneously is undefined.

**Comment by prestonvanloon** [comment]
It's called once from the go init() function, I think. We're not 100% sure and this issue isn't reproducible.

**Comment by herumi** [comment]
The test on Travis-ci has never shown the error with ASan, so I suspect that it is a false negative.
But I'll check it, then could you tell me how to exec the fuzzing?

**Comment by herumi** [comment]
The problem has not reproduced, so I close this.
